apiVersion: v1
kind: Secret
metadata:
  name: mountainhub-secrets
  namespace: mountainhub
type: Opaque
stringData:
  SUPABASE_URL: "{{ secrets.SUPABASE_URL }}"
  SUPABASE_KEY: "{{ secrets.SUPABASE_KEY }}"
  SUPABASE_BUCKET_GPX: "gpx-files"
  SUPABASE_BUCKET_MEDIA: "media-files"
