apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: mountainhub
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  # ClusterIP — only reachable internally by the api-gateway
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
